export const lightColor = {
  background: '#FFFFFF',
  text: '#000000',
  primaryblue: '#1877F2',
  fromcolor: '#AEA9A9',
  dashcolor: '#CCCCCC',
  white: '#FFFFFF',
  paginationbackground: '#222',
  black: '#000000',
  inputTextBackground: '#E8E6E6',
  inputTextBorder: '#E0DDDD',
  placeholderTextColor: '#000000',
  commentTextStyle: '#757575',
  modalBorderStyle: '#D9D9D9',
  darwerTint: '#00000',
  darwerTintBackground: '#e2e5e9',
};

export const darkColor = {
  background: '#1A1A1A',
  text: '#FAFAFA',
  primaryblue: '#1877F2',
  fromcolor: '#FFFFFF',
  dashcolor: '#CCCCCC',
  white: '#FFFFFF',
  paginationbackground: '#aaa',
  black: '#000000',
  inputTextBackground: '#E8E6E6',
  inputTextBorder: '#E0DDDD',
  placeholderTextColor: '#000000',
  commentTextStyle: '#757575',
  modalBorderStyle: '#D9D9D9',
  darwerTint: '#FFFFFF',
  darwerTintBackground: '#2d2e31',
};
